function view_planes(FName)
% Visual Tool for viewing planes of images in Matlab
% FName is name of file to view
%
% Opens image and puts data into UserData fields
% Userdata fields are:
% DIMS <- t_DIM   (DIMS = [DIM ORIGIN VOX])
% img <- b_disp
% IF <- b_Quit;

% Matlab version specifics
v = version;
if v(1) == '5'
  son = 'On';
else
  son = 'Yes';
end

% Figure for display
IF = figure('name', ['Plane viewer for file ' FName]);
colormap('bone');

% Figure with buttons etc
F=figure('Units', 'Normalized',...
   'Position',[0.05 0.05 0.15 0.3],...
   'name',[FName]);

t_FName = uicontrol('Style','Text',...
   'String',FName,...
   'HorizontalAlignment', 'Right', ...
   'BackGroundColor',[0 0 0],...
   'ForeGroundColor','w',...
   'Units','Normalized',...
   'UserData', FName, ...
   'Position',[0.1,0.85,0.8,0.1]);

m_orient = uicontrol('Style','Popup',...
   'String', 'Sagittal|Coronal|Axial',...
   'Units','Normalized',...
   'Position',[0.1, 0.71, 0.8, 0.1],...
   'Value', 1, ...
   'Callback','view_planes_cb(''LoadData'')'...
   );

t_ORIG = uicontrol('Style','Text',...
   'String','Plane',...
   'BackGroundColor',[0.35 0.35 0.35],...
   'ForeGroundColor','w',...
   'Units','Normalized',...
   'Position',[0.1,0.6,0.40,0.10]);

t_DIM = uicontrol('Style','Edit',...
   'String','1',...
   'BackGroundColor',[1 1 1],...
   'ForeGroundColor','b',...
   'Units','Normalized',...
   'Position',[0.6,0.6,0.3,0.10],...
   'Callback', 'view_planes_cb(''CheckPlane''); view_planes_cb(''ShowPlane'', 1)');

sl_plane = uicontrol('Style','Slider',...
   'Value',1,...
   'Min', 1, ...
   'Max', 2, ...
   'Units','Normalized',...
   'Position',[0.1 0.45 0.8 0.10],...
   'HorizontalAlignment','Left',...
   'Callback', 'view_planes_cb(''SetPlane''); view_planes_cb(''ShowPlane'', 1)'...
   );

b_disp = uicontrol('Style','PushButton',...
   'String','Redisplay',...
   'BackGroundColor',[1 1 1],...
   'ForeGroundColor','b',...
   'Interruptible',son,...
   'Units','Normalized',...
   'Position',[0.1,0.25,0.8,0.15],...
   'Callback','view_planes_cb(''ShowPlane'', 0)');

b_Quit = uicontrol('Style','PushButton',...
   'String','Quit',...
   'Interruptible',son,...
   'BackGroundColor',[0.7 0 0],...
   'ForeGroundColor','w',...
   'Units','Normalized',...
   'Position',[0.1,0.05,0.8,0.15],...
   'Callback','view_planes_cb(''Quit'')', ...
   'UserData', IF);

set(F, 'UserData', [t_FName b_disp t_ORIG sl_plane m_orient t_DIM b_Quit]);

set(m_orient, 'Value', 1);

view_planes_cb('LoadData');
